### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by celocore** [H2-invent/jitsi-admin#263] opened 2021-12-15 08:29 UTC
Hello,

because I don't know how to reopen a closed issue, I am recreating this one.
I have the same problem as in issue #259. After setting up and configuring a jitsi-admin and a keycloak server, I am redirected between the jitsi-admin and the keycloak server in ping-pong mode after calling the jitsi-admin.

I'm working with jitsi-admin 0.71.5, keycloak 15.1.0, apache 2.4, MariaDB 10.3.32, php 7.4. ubuntu 20.04

**Comment by celocore** [comment] 2021-12-16 06:56
After doing some more tests, I found that the problem only occurs from version 0.71.0 upwards. The versions before that (tested 0.69.6 - 0.70.7) run without problems.

**Comment by holema** [comment] 2021-12-18 13:02
Hello @celocore,

this can happen, becuse the Keycloak guard is completly new written.
In our productive system we had no problems with this Ping pong effect. We only had problems when someone wants to register. But this should be fixed in 0.71.4

Do you use the group-mapper to controll which group is allowed to create conferences?
when yes, please doublecheck if the mapper is called groups. 
We had this issue when there was a type in the mapper.

When the error still occurs, can you please send me an email to entwicklung@h2-invent.com, so we can look together what the issue is.

**Comment by holema** [comment] 2021-12-22 08:47
Hello @celocore,

could you solve the problem?

Best regards
Emanuel

**Comment by holema** [comment] 2022-01-05 11:55
Hello @celocore,
could you delete all sessins fom the keycloak. maybe this helps.

Best regards

**Comment by holema** [comment] 2022-01-26 09:37
Hello I think I found the solution.
You have to create a new Mapper in the client:
![image](https://user-images.githubusercontent.com/22790152/151138976-baaf6523-8ac9-471e-bf94-03bc932e3288.png)

**Comment by celocore** [comment] 2022-02-02 08:29
Hello @holema,

sorry for the long delay in replying. Unfortunately I am heavily involved in other projects at the moment.
As a temporary workaround we are using jitsi-admin in version 0.70.7. I will check your hints and let you know as soon as possible.

Best regards

**Comment by holema** [comment] 2022-02-10 08:44
this is fixed in #259 
I close this now

**Closed by holema** 2022-02-10 08:44 UTC
