### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by timololipop** [H2-invent/jitsi-admin#259] opened 2021-12-05 17:06 UTC
Hello,

I am receiving this message since updating Jitsi Admin. Any idea where this problem could occure? Either at keycloak or nginx?

My env.local:
DATABASE_URL=mysql://jitsi:asdasdasd@localhost:3306/jitsi
DATABSE_SERVER=<mariadb-10.1.0>

###> symfony/framework-bundle ###
APP_ENV=prod
APP_DEBUG=0
APP_SECRET=asdasdasdasd

###> symfony/swift_mailer ###
MAILER_HOST=asdasdasd.hostgator.com
MAILER_PORT=465
MAILER_PASSWORD=aasdasdasd
MAILER_USERNAME=invite@asdasd.com
MAILER_ENCRYPTION=ssl
MAILER_TRANSPORT=smtp
DEV_EMAIL=invite@asdasd.com
###ODC Parameters###
imprint=</impressum>
dataPrivacy=</datenschutzhinweis>
helpUrl=</help>

###Cron Parameters###
CRON_TOKEN=<sha256>
CRON_IPADRESS=127.0.0.1

###Emails###
registerEmailName=invite@asdasd.com
DEV_EMAIL=invite@asdasd.com
DEFAULT_EMAIL=invite@asdasd.com

TRUSTED_PROXIES=127.0.0.1

###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=jitsi
OAUTH_KEYCLOAK_CLIENT_SECRET=asdasdasd
OAUTH_KEYCLOAK_SERVER=https://asdasdasd/auth
OAUTH_KEYCLOAK_REALM=master
###< hwi/oauth-bundle ###

###> demo ###
demo_installation=prod
###< demo ###

###> matomo ###
matomo_enable=false
matomo_id=1
matomo_url=analytics.local.com
###< matomo ###

###> LaF ###
laF_bbb=0
laF_startpage=false
laF_onlyRegisteredParticipents=0
laF_version=2.0.0-dev
laF_pexel_api_key=#EnterAPIKeyHere
laF_pexel_refresh_time=1200
laF_baseUrl=https://invite.asdasd.com
laF_emailTextLogin=1
laf_CreateServerOpenToEveryone=1
laf_keycloakGroupToCreateServer=/user
laf_administratorEmail=invite@asdasd.com
laf_notificationUrl=""
laf_bbb_Url=""
###< LaF ###

###> Default Jitsi Server ###
default_jitsi_server_id=1
###< Default Jitsi Server ###

My nginx conf:

server {
   listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/invite.asdasd.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/invite.asdasd.com/privkey.pem;
  ssl_session_timeout 5m;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
  ssl_prefer_server_ciphers on;

   server_name invite.asdasd.com;
   root /var/www/jitsi-admin/public;
   location / {
       try_files $uri /index.php$is_args$args;
   }
   location ~ ^/index\.php(/|$) {
       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
       fastcgi_split_path_info ^(.+\.php)(/.*)$;
       include fastcgi_params;
       fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
       fastcgi_param DOCUMENT_ROOT $realpath_root;
       internal;
   }
   location ~ \.php$ {
       return 404;
   }
   error_log /var/log/nginx/symfony_error.log;
   access_log /var/log/nginx/symfony_access.log;
}
server {
    listen 80;

    server_name invite.asdasdasd.com;

    return 301 https://$host$request_uri;
}

Thanks.

**Comment by timololipop** [comment] 2021-12-05 17:37
Btw, getting an old version from Aug doesnt throw this problem.

**Comment by holema** [comment] 2021-12-06 08:48
Hello @timololipop,
this is a strange problem.
Can you write me the URL to entwicklung@h2-invent.com. then I can controll the redirects an can take a deeper look at it.
I need to take a look in the network section of my browser to see which controller redirects.
In our environment the migration was working with no problems at all.

Bet regads

**Comment by holema** [comment] 2021-12-06 08:50
@timololipop 
Or you can send me the Logs from Symfony which are located in the /var/log/prod.log directory

**Comment by holema** [comment] 2021-12-08 19:53
Hello @timololipop,
could you find a solution for this issue?

**Comment by timololipop** [comment] 2021-12-08 20:03
Hey, I downgraded the host system now and didnt have the time yet to update it again for you to test, I will reach out to you once I face it again. Thank you

**Comment by celocore** [comment] 2021-12-15 07:47
Hello,

I would like to take up this problem again, as I am facing the same. However, I have not upgraded, but have set up a new installation with the current github version + Keycloak 15.1.

**Comment by holema** [comment] 2022-01-20 07:39
#187

**Comment by bienxanh1901** [comment] 2022-02-09 04:14
Hello, Did we resolve this issue in release #0.71.14 ?

**Comment by holema** [comment] 2022-02-09 08:01
Hello @bienxanh1901,
do you use apache or nginx as an webserver?
I can not reproduce the error, but I only use apache as webserver in all deployments.

Best regards
EManuel

**Comment by bienxanh1901** [comment] 2022-02-09 08:06
> 

Hi @holema,
I use nginx as an web server.
this is the server config:

```
server {
   listen 443 ssl;
   server_name localhost;
   ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
   ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
   ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers         HIGH:!aNULL:!MD5;
   root /home/jitsi/jitsi-admin-0.70.7/public;
   location / {
       try_files $uri /index.php$is_args$args;
   }
   location ~ ^/index\.php(/|$) {
       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
       fastcgi_split_path_info ^(.+\.php)(/.*)$;
       include fastcgi_params;
       fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
       fastcgi_param DOCUMENT_ROOT $realpath_root;
       internal;
   }
   location ~ \.php$ {
       return 404;
   }
   error_log /var/log/nginx/symfony_error.log;
   access_log /var/log/nginx/symfony_access.log;
}
```

**Comment by holema** [comment] 2022-02-09 14:16
Thanks for the Config.
The Problem is, that I never use nginx, so I don`t know where to start searching.

Have you tried to change the system to development mode?
Can you post the logs here which are in the var/log/prod.log file.

**Comment by holema** [comment] 2022-02-09 15:35
Hello @bienxanh1901 
I think today we found the sollution.
Did you migrate the database? 
This is so important, because if not then the Jitsi-Admin throws exyctly this error. And this is also the reason why it worked with the old version, because the database schema is matching.

to migrate the Jitsi-Admin please enter:
`php bin/console doc:mig:mig` in the cli.

**Comment by bienxanh1901** [comment] 2022-02-10 07:38
Hi @holema,
I don't think so. I use new empty database for testing new release.

I also tried with apache2 but same issue occur.

This is log file: [dev.log](https://github.com/H2-invent/jitsi-admin/files/8038947/dev.log)

This is my ldap config:
```
### LDAP Settings ###
ldap_url="ldap://localhost:389"
ldap_bind_dn="cn=admin,dc=example,dc=org"
ldap_password="admin"
ldap_user_dn="ou=users,dc=example,dc=org"
ldap_user_object_classes="inetOrgPerson,top"
ldap_search_scope="sub"
ldap_userName_attribute="uid"
ldap_attribute_mapper='{"firstName":"givenName", "lastName":"sn", "email":"mail"}'
ldap_bind_type="simple"
ldap_rdn_ldap_attribute="cn"
ldap_uuid_ldap_attribute="uid"
ldap_server_individualName="ldap_1"
###<LDAP Settings>###
```

This is url for authenticating by keycloak:
`http://localhost:8080/auth/realms/jitsi/protocol/openid-connect/auth?scope=email&state=fde9d8c265184fac6901e077580730d3&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Flocalhost%2Findex.php%2Flogin%2Fkeycloak_login%2Fcheck&client_id=jitsi`

**Comment by holema** [comment] 2022-02-10 08:21
Okay, here I see two things:
Is this env set in your Environment? 
strict_allow_user_creation=1
This has to be set to 1 otherwise jitsi-admin will not create any new user which are new from the keycloak.
The Logic behind this:
1. The JItsi-Admin syncy all his users from the LDAP with the command `app:ldap:sync` Now the Jitsi-Admin takes all the user from the LDAP and creates the coresponding user in the LDAP. 
2. The User l now logins via keycloak. in the best case here is the same LDAP as identity provider. and now the user is redirected to the jitsi-admin with the prefered-username. this has to match with the uid you set here in ldap_userName_attribute.

I just found an error in the env.sample. Here is the strict_allow_user_creation parameter set to 0. In this case if the user is not imported via the LDAP sync command it is not generated. 
Just change the strict_allow_user_creation paramter to 1 then it will work.

I will fix the env.sample in a minute.

Best regards

**Comment by bienxanh1901** [comment] 2022-02-10 08:35
hello @holema,
Yeah It's working now.
Thank you very much for your solution!

Best Regards

**Comment by holema** [comment] 2022-02-10 08:40
@bienxanh1901 I´m so happy we found the sollution.
I close this issue now :)
Have fun. 
I mentioned you in the latest release :)

**Closed by holema** 2022-02-10 08:40 UTC
