### ISSUE TITLE
500-error with docker installation

### ISSUE THREAD

**Issue by frippe15** [H2-invent/jitsi-admin#353] opened 2022-11-15 08:54 UTC
**Describe the bug**
After docker install, keycloak logon is working, but trying to login to jitsi-admin gives 500-error, tried both a local keycloak account and saml/oath using azure AD.

![jitsi-1](https://user-images.githubusercontent.com/58766304/201875441-08641b9d-be5a-4d81-bac4-3b326b50aecd.png)
![jitsi2](https://user-images.githubusercontent.com/58766304/201875453-aa205339-068c-4499-a690-4991c3064aec.png)

**Comment by holema** [comment] 2022-11-17 10:48
Thanks for the hint. here is a problem with Keycloak 20 Can you check which Keycloak Version is installed? It seems that here is KC 20 installed.

**Comment by holema** [comment] 2022-11-17 10:56
@frippe15,

can you send me the logs of the application docker container?

**Comment by holema** [comment] 2022-11-17 11:01
You screenshots gave me a hint. Do you use letsEncrypt? or do you use sefsigned certificats?

You Browser tells you that your certs are not valid. So the Jitsi-Admin in the background wants to talk to the keycloak to get the user informations in the background. this is not possible, because the SSL-Certificate is not valid.

**Comment by frippe15** [comment] 2022-11-17 13:09
Hi, 
I have cloned and running the latest docker images from here. Keycloak version seems to be 16.1.1. 
I don´t use lets encrypt, I guess when you run installDocker and say use https, a self signed is created? Can´t seem to find any way to use my own cert for keycloak docker container?

**Comment by frippe15** [comment] 2022-11-17 13:20
Logs from app container:
{"log":"172.18.0.2 - - [17/Nov/2022:14:17:04 +0100] \"GET / HTTP/1.1\" 302 538 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\"\n","stream":"stdout","time":"2022-11-17T13:17:04.620652543Z"}
{"log":"172.18.0.2 - - [17/Nov/2022:14:17:04 +0100] \"GET /m HTTP/1.1\" 302 603 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\"\n","stream":"stdout","time":"2022-11-17T13:17:04.663050648Z"}
{"log":"172.18.0.2 - - [17/Nov/2022:14:17:04 +0100] \"GET /room/dashboard HTTP/1.1\" 302 558 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\"\n","stream":"stdout","time":"2022-11-17T13:17:04.686551753Z"}
{"log":"172.18.0.2 - - [17/Nov/2022:14:17:04 +0100] \"GET /login HTTP/1.1\" 302 2019 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\"\n","stream":"stdout","time":"2022-11-17T13:17:04.7113779Z"}
{"log":"172.18.0.2 - - [17/Nov/2022:14:17:04 +0100] \"GET /login/keycloak_login/check?state=a28b272884e5a35ce25408736483b72a\u0026session_state=b37bf44c-6119-42c5-871f-34b31c7e275e\u0026code=b07223c3-7da9-47d7-95f1-cc20c5d1541e.b37bf44c-6119-42c5-871f-34b31c7e275e.e0d7a685-a075-4834-a6ca-cb40d734f4af HTTP/1.1\" 500 1136 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\"\n","stream":"stdout","time":"2022-11-17T13:17:04.783795737Z"}
{"log":"172.18.0.2 - - [17/Nov/2022:14:17:04 +0100] \"GET /favicon.ico HTTP/1.1\" 200 159287 \"https://jitsiadmin.domain.com/login/keycloak_login/check?state=a28b272884e5a35ce25408736483b72a\u0026session_state=b37bf44c-6119-42c5-871f-34b31c7e275e\u0026code=b07223c3-7da9-47d7-95f1-cc20c5d1541e.b37bf44c-6119-42c5-871f-34b31c7e275e.e0d7a685-a075-4834-a6ca-cb40d734f4af\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\"\n","stream":"stdout","time":"2022-11-17T13:17:04.807104264Z"}
{"log":"127.0.0.1 - - [17/Nov/2022:14:17:05 +0100] \"GET /health/check HTTP/1.1\" 200 371 \"-\" \"curl/7.68.0\"\n","stream":"stdout","time":"2022-11-17T13:17:05.516674535Z"}

**Comment by holema** [comment] 2022-11-17 14:58
Hello @frippe15,

do you want to test the jitsi-admin in you local development environment? then you should use http, not https.

If you install it on a standalone server, then you should use letsencrypt. The selfsigned Certificat is not trusted so this error ocurs.

If you use a loadbalancer in front of the jitsi-admin, then it will get much more complicated, because then you need an internal DNS.

The Keycloak should be correct and is the same version I`m running and is tested.

**Comment by holema** [comment] 2022-12-27 10:51
I will close this issue. If the issue is still ongoing please reopen it.

**Closed by holema** 2022-12-27 10:51 UTC
